# -*- coding: utf-8 -*-
import math

# Координаты зон (для прототипа в комнате 2x1 метр)
HOME_POSITION = (0.2, 0.5)
WAREHOUSE_ZONE = (1.65, 0.5)
DELIVERY_ZONE_RADIUS = 0.5

# Параметры навигации
POSITION_TOLERANCE = 0.05
CUSTOMER_APPROACH_DISTANCE = 0.25
MAX_SPEED = 120
MIN_SPEED = 40
LOCALIZATION_UPDATE_RATE = 5
NAVIGATION_UPDATE_RATE = 10
MAX_STUCK_TIME = 30.0
STUCK_THRESHOLD = 0.05

# LiDAR
LIDAR_PORT = '/dev/ttyUSB0'
LIDAR_BAUDRATE = 230400
PERSON_DETECTION_MIN_POINTS = 30
PERSON_DETECTION_CLUSTER_DISTANCE = 0.5
PERSON_MIN_CLUSTER_SIZE = 0.05
PERSON_MAX_CLUSTER_SIZE = 2.0
OBSTACLE_MIN_DISTANCE = 0.05
LIDAR_MAX_RANGE = 12
LIDAR_MIN_RANGE = 0.03

# Одометрия (для прототипа 16x19см)
WHEEL_BASE = 0.14
WHEEL_RADIUS = 0.03
ENCODER_TICKS_PER_REVOLUTION = 360

# Последовательная связь (для Linux)
ARDUINO_PORT = '/dev/ttyACM0'
ARDUINO_BAUDRATE = 9600
SERIAL_TIMEOUT = 0.5
SERIAL_MAX_RETRIES = 3
SERIAL_COMMAND_QUEUE_SIZE = 10

# Доставка
DELIVERY_TIMEOUT = 10.0
LOADING_CONFIRMATION_TIMEOUT = 60.0
QR_SCAN_TIMEOUT = 20.0

# Аудио
AUDIO_DIR = 'assets/audio'
AUDIO_REQUEST_QR = 'request_qr.wav'
AUDIO_ORDER_ACCEPTED = 'order_accepted.wav'
AUDIO_ORDER_REJECTED = 'order_rejected.wav'
AUDIO_DELIVERY_GREETING = 'delivery_greeting.wav'
AUDIO_SUCCESS_SCAN = 'successScan.wav'
AUDIO_FAILURE_SCAN = 'failureScan.wav'
AUDIO_ERROR = 'error.wav'

# База данных
DATABASE_URL = "sqlite:///assets/orders.db"

# Сервопривод
BOX_OPEN_ANGLE = 90
BOX_CLOSE_ANGLE = 0
SERVO_SPEED = 45

# Карта (для комнаты 2x1 метр)
MAP_FILE = 'assets/maps/warehouse_map.yaml'
MAP_RESOLUTION = 0.02
MAP_WIDTH = 2.0
MAP_HEIGHT = 1.0

# Фильтр частиц
NUM_PARTICLES = 50
MOTION_NOISE_TRANSLATION = 0.01
MOTION_NOISE_ROTATION = 0.03
MEASUREMENT_NOISE = 0.05
RESAMPLE_THRESHOLD = 0.5

# Планирование пути
OBSTACLE_CLEARANCE = 0.10
PLANNING_STEP_SIZE = 0.05
MAX_PLANNING_ITERATIONS = 5000

# PID контроллер
PID_LINEAR_KP = 1.0
PID_LINEAR_KI = 0.0
PID_LINEAR_KD = 0.1
PID_ANGULAR_KP = 2.0
PID_ANGULAR_KI = 0.0
PID_ANGULAR_KD = 0.2

# Логирование
LOG_LEVEL = 'INFO'
LOG_FILE = 'relaybot.log'
LOG_MAX_SIZE = 10 * 1024 * 1024
LOG_BACKUP_COUNT = 5

# Восстановление после ошибок
MAX_RECOVERY_ATTEMPTS = 3
RECOVERY_RETRY_DELAY = 2.0
MAX_RECOVERY_TIME = 60.0

# Таймауты состояний
STATE_TIMEOUT_WAITING = 0
STATE_TIMEOUT_APPROACHING = 60.0
STATE_TIMEOUT_VERIFYING = 30.0
STATE_TIMEOUT_NAVIGATING_TO_WAREHOUSE = 120.0
STATE_TIMEOUT_LOADING = 60.0
STATE_TIMEOUT_RETURNING_TO_CUSTOMER = 120.0
STATE_TIMEOUT_DELIVERING = 15.0
STATE_TIMEOUT_RESETTING = 120.0
STATE_TIMEOUT_ERROR_RECOVERY = 180.0

# IR сенсор
IR_EMERGENCY_STOP_DISTANCE = 0.1
IR_WARNING_DISTANCE = 0.3

# Константы
PI = math.pi
TWO_PI = 2 * math.pi
DEG_TO_RAD = math.pi / 180.0
RAD_TO_DEG = 180.0 / math.pi
